### ISSUE TITLE
meltano pipeline error

### ISSUE THREAD

**Issue by n0012** [matsonj/nba-monte-carlo#37]
I'm attempting to run on a mac within pyenv (python version 3.8.15).  No problem running 'make build'.  However running into an error running 'make pipeline'.  See Meltano Logs below.  Seems like it might relate to python 3.8 multiprocessing issue which is a dependency of target-parquet.  Any tips?

Meltano Logs

2022-11-15T22:36:12.680915Z [info     ] Performing full refresh, ignoring state left behind by any previous runs.
2022-11-15T22:36:13.985106Z [info     ] INFO Using supplied catalog /Users/<user>/dev/meltano-projects/nba-monte-carlo/.meltano/run/tap-spreadsheets-anywhere/tap.properties.json. cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.985599Z [info     ] INFO Processing 4 selected streams from Catalog cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.985788Z [info     ] INFO Syncing stream:nba_schedule_2023 cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.995274Z [info     ] INFO Walking ./data.           cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.995459Z [info     ] INFO Found 3 files.            cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.995631Z [info     ] INFO Checking 3 resolved objects for any that match regular expression "nba_schedule_2023.csv" and were modified since 2001-01-01 00:00:00+00:00 cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.998637Z [info     ] INFO Processing 1 resolved objects that met our criteria. Enable debug verbosity logging for more details. cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:13.998865Z [info     ] INFO Syncing file "nba_schedule_2023.csv". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.109560Z [info     ] INFO Sending version information to singer.io. To disable sending anonymous usage data, set the config parameter "disable_collection" to true cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.110472Z [info     ] INFO writing streams in separate folders cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126474Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126637Z [info     ]   File "/Users/<user>/dev/meltano-projects/nba-monte-carlo/.meltano/loaders/target-parquet/venv/bin/target-parquet", line 8, in <module> cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126707Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126767Z [info     ]   File "/Users/<user>/dev/meltano-projects/nba-monte-carlo/.meltano/loaders/target-parquet/venv/lib/python3.8/site-packages/target_parquet/__init__.py", line 274, in main cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126826Z [info     ]     state = persist_messages(  cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126882Z [info     ]   File "/Users/<user>/dev/meltano-projects/nba-monte-carlo/.meltano/loaders/target-parquet/venv/lib/python3.8/site-packages/target_parquet/__init__.py", line 225, in persist_messages cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126936Z [info     ]     t2.start()                 cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.126989Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/process.py", line 121, in start cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127063Z [info     ]     self._popen = self._Popen(self) cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127114Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/context.py", line 224, in _Popen cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127167Z [info     ]     return _default_context.get_context().Process._Popen(process_obj) cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127219Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/context.py", line 284, in _Popen cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127268Z [info     ]     return Popen(process_obj)  cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127317Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__ cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127366Z [info     ]     super().__init__(process_obj) cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127415Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__ cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127466Z [info     ]     self._launch(process_obj)  cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127514Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127565Z [info     ]     reduction.dump(process_obj, fp) cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127614Z [info     ]   File "/Users/<user>/.pyenv/versions/3.8.15/lib/python3.8/multiprocessing/reduction.py", line 60, in dump cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127663Z [info     ]     ForkingPickler(file, protocol).dump(obj) cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.127713Z [info     ] AttributeError: Can't pickle local object 'persist_messages.<locals>.consumer' cmd_type=elb consumer=True name=target-parquet producer=False stdio=stderr string_id=target-parquet
2022-11-15T22:36:14.142130Z [info     ] INFO Wrote 1341 records for stream "nba_schedule_2023". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.142359Z [info     ] INFO Syncing stream:team_ratings cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.142598Z [info     ] INFO Walking ./data.           cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.142795Z [info     ] INFO Found 3 files.            cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.143263Z [info     ] INFO Checking 3 resolved objects for any that match regular expression "team_ratings.csv" and were modified since 2001-01-01 00:00:00+00:00 cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.143363Z [info     ] INFO Processing 1 resolved objects that met our criteria. Enable debug verbosity logging for more details. cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.143426Z [info     ] INFO Syncing file "team_ratings.csv". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.144764Z [info     ] INFO Wrote 30 records for stream "team_ratings". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.144874Z [info     ] INFO Syncing stream:xf_series_to_seed cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145051Z [info     ] INFO Walking ./data.           cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145115Z [info     ] INFO Found 3 files.            cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145438Z [info     ] INFO Checking 3 resolved objects for any that match regular expression "xf_series_to_seed.csv" and were modified since 2001-01-01 00:00:00+00:00 cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145510Z [info     ] INFO Processing 1 resolved objects that met our criteria. Enable debug verbosity logging for more details. cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145568Z [info     ] INFO Syncing file "xf_series_to_seed.csv". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145835Z [info     ] INFO Wrote 14 records for stream "xf_series_to_seed". cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.145935Z [info     ] INFO Syncing stream:nba_elo_latest cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.146058Z [info     ] INFO Assembled https://projects.fivethirtyeight.com/nba-model/nba_elo_latest.csv as the URL to a source file. cmd_type=elb consumer=False name=tap-spreadsheets-anywhere producer=True stdio=stderr string_id=tap-spreadsheets-anywhere
2022-11-15T22:36:14.337744Z [error    ] Loader failed                  
Traceback (most recent call last):
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/logging/output_logger.py", line 201, in redirect_logging
    yield
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 457, in run
    await self.run_with_job()
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 483, in run_with_job
    await self.execute()
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 449, in execute
    await manager.run()
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 647, in run
    _check_exit_codes(
  File "/Users/<user>/.pyenv/versions/3.8.15/envs/meltano/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 799, in _check_exit_codes
    raise RunnerError("Loader failed", {PluginType.LOADERS: consumer_code})
meltano.core.runner.RunnerError: Loader failed
2022-11-15T22:36:14.338209Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False

**Comment by matsonj** [comment]
Thanks for surfacing this. I’ll see if I can repro and get a fix in. I don’t see any open issues in the target, which is where I would expect to see something if this were an issue with python 3.8. https://github.com/estrategiahq/target-parquet

**Comment by matsonj** [comment]
My main tip is “run it in codespaces” since that is the env I’m developing in, but that may or may not work for you.

**Comment by matsonj** [comment]
We just dropped in a [docker container](https://github.com/matsonj/nba-monte-carlo/pull/38), do you want to try that?

**Comment by n0012** [comment]
Thanks I'll give the docker container a shot and let you know

**Comment by n0012** [comment]
The docker workflow allows me to run the meltano pipeline on my M1 macbook pro.  Thanks you.  Is the plan to also create docker command to run the superset UI?  It seems the conformed duckdb files are left in the container after pipeline run (as opposed to using a docker volume to send back to the host).

**Comment by matsonj** [comment]
@n0012 re:superset, hold that thought. I am working on landing something inside the meltano workflow so the reports/visuals are served from the docker container. But I am blocked by some external dependencies in node etc. The idea long term is to ship the files to a data lake for analysis, so i'm not too keen on moving them back to the back to the host if I can avoid it.

**Comment by n0012** [comment]
Sounds like a good plan.  I'll keep an eye out on the repo for docker updates.  Thanks!
