### ISSUE TITLE
update to support duckdb 0.7.0

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#78]

**Comment by matsonj** [comment]
blocked on this until evidence supports version 43 (0.7.0), but everything else looks good!

**Comment by matsonj** [comment]
ah actually not blocking, can use Buenavista courtesy of @jwills. ok putting this together now.

**Comment by matsonj** [comment]
ah crap running into an error with BV, I think bc the folder structure for the dbt project varies when using meltano compared to a "standard" dbt project.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.local/lib/python3.9/site-packages/duckdbt/server.py", line 79, in <module>
    raw_profile = raw_profiles[profile_name]
KeyError: 'meltano'
```

so then of course i duplicated the dbt profile into the /transform directory to see if i get a different error:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.local/lib/python3.9/site-packages/duckdbt/server.py", line 94, in <module>
    base_profile_dict = Profile.from_raw_profiles(
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/profile.py", line 392, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/profile.py", line 336, in from_raw_profile_info
    target_name, profile_data = cls.render_profile(
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/profile.py", line 299, in render_profile
    profile_data = renderer.render_data(raw_profile_data)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/renderer.py", line 49, in render_data
    return deep_map_render(self.render_entry, data)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/utils.py", line 228, in deep_map_render
    return _deep_map_render(func, value, ())
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/utils.py", line 194, in _deep_map_render
    ret = {k: _deep_map_render(func, v, (keypath + (str(k),))) for k, v in value.items()}
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/utils.py", line 194, in <dictcomp>
    ret = {k: _deep_map_render(func, v, (keypath + (str(k),))) for k, v in value.items()}
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/utils.py", line 196, in _deep_map_render
    ret = func(value, keypath)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/renderer.py", line 33, in render_entry
    return self.render_value(value, keypath)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/renderer.py", line 184, in render_value
    rendered = super().render_value(value, keypath)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/config/renderer.py", line 42, in render_value
    return get_rendered(value, self.context, native=True)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 587, in get_rendered
    return render_template(template, ctx, node)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 542, in render_template
    return template.render(ctx)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 183, in render
    return self.environment.handle_exception()
  File "/home/vscode/.local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 140, in quoted_native_concat
    head = list(islice(nodes, 2))
  File "<template>", line 1, in top-level template code
  File "/home/vscode/.local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/context/secret.py", line 54, in env_var
    raise_parsing_error(msg)
  File "/home/vscode/.local/lib/python3.9/site-packages/dbt/exceptions.py", line 449, in raise_parsing_error
    raise ParsingException(msg, node)
dbt.exceptions.ParsingException: Parsing Error
  Env var required but not provided: 'MELTANO_PROJECT_ROOT'
```
  
  Basically need to "meltano-ize" Buenavista or wait for the node stuff to update to 0.7.0

**Comment by matsonj** [comment]
btw open to thoughts here...

**Comment by jwills** [comment]
Works great in my fork 💅

**Comment by gregwdata** [comment]
Evidence 13.0.0 just released to npm - it includes duckdb dependency update to use 0.7.1 https://github.com/evidence-dev/evidence/pull/654

**Comment by gregwdata** [comment]
There were some non-DuckDB-related depenency issues with the 13.X releases. Looks like they just got them ironed out and released 14.0.0. Just tested the Evidence template project with a migrated `.duckdb` (PR pending https://github.com/evidence-dev/template/pull/36 ) and it works with a 0.7.X file now. You'll want to set your Evidence dependency to `"^14.0.0"` and change the `dev` script in `analyze/package.json` to `"evidence dev --open"` (the `-o` flag doesn't work in the new version of vite)

**Comment by matsonj** [comment]
```npm run dev``` isn't working in my codespace (networking issue, looking to be associated with 14.0.0) so I'm pushing to live to check if it works haha. This might break.

**Comment by matsonj** [comment]
closing as completed! its updated!
